### ISSUE TITLE
Question about operative system and ROS version

### ISSUE THREAD

**Issue by bag-mt** [ETHZ-RobotX/SuperMegaBot#2]
Good morning,

I am a PhD student that will participate at the ETH Robotics Summer School. I am asking this question because I replyed to your email about the software environment but I have not recevied an answer. I want to ask you if my software configuration works well for the Summer School: I have Ubuntu 18 and ROS Melodic installed on it; I have already started on it the ROS tutorial exercises suggested for the Summer School.

I ask you if my current installation is good since I work a PC provided by my University and so I have found the Ubuntu 18 already installed, along with Windows, and I would not prefer to install another OS on this PC. In the other case I would need to reinstall the Ubuntu OS and the software from the beginning. Therefore I ask you if my current PC is ok or if Ubuntu 20 and ROS Noetic are really making the difference.

Thank you in advance

**Comment by mantelt** [comment]
Hi,

thank you taking care of setting up the software environment in time and for reaching out here. Like that, others with a similar question get the chance to see this answer.

But to actually answer your question:
We developed the software environment under ROS Noetic on Ubuntu 20.04 and have not performed any tests on any other combination of OS and ROS versions. Since ROS Melodic is still using Python 2, I think it is rather unlikely that it will work out of the box. 

You may of course try yourself before either upgrading to Ubuntu 20.04, installing 20.04 nevertheless alongside the other 2 OS (which actually works flawlessly on my computer) or trying to install 20.04 on an external hard drive, which apparently also works decently if you have a good external drive.

But I hope you'll understand that we can't give support for all the possible varieties of installations one can think of except for the one we actually suggest.

Best regards,
Thomas

**Comment by eliabntt** [comment]
Maybe you can try to use Windows Linux subsystem (2) using Ubuntu 20.04. That could work and, with an x11 server, you have even the gui of gazebo(not that sure but 99%)/rviz(sure, I've used this).
