### ISSUE TITLE
vcs import password

### ISSUE THREAD

**Issue by er1c-cartman** [ETHZ-RobotX/SuperMegaBot#46]
for importing link on tutorial, it requires password. So I couldn't download the whole package and i think because of this, I couldn't build the package perfectly

vcs import \
--recursive \
--input https://raw.githubusercontent.com/ETHZ-RobotX/SuperMegaBot/master/smb.repos .

/usr/bin/vcs:6: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import load_entry_point
...............Password for 'https://nubertj@bitbucket.org': ............

**Comment by mantelt** [comment]
Hi

Thank you for reaching out. This problem is actually known and is because of part of the software that has been made available during the Robotics Summer School, but hasn't been officially released yet. As this is still an ongoing process, there is not much I can do right now to help you, sorry. This issue affects only the mapping and localization (SLAM) part of the software. Everything else should run nevertheless.

**Comment by er1c-cartman** [comment]
thx for answering :)
btw, 1 question.
is traversability planner is well working??
I tried to change some parameters to do implementation on husky robot.
but lack of my ability, it's bit hard and not working I guess
can u give me some help if it's possible?
best regards
